# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: knowledge.proto for package 'knowledge'

require 'grpc'
require_relative '../pbs/knowledge_pb'

module Knowledge
  module Presentation
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'knowledge.Presentation'

      rpc :Register, ::Knowledge::Request, ::Knowledge::Response
    end

    Stub = Service.rpc_stub_class
  end
end
