# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: knowledge.proto for package 'knowledge'

require 'grpc'
require 'knowledge_pb'

module Knowledge
  module Presentation
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'knowledge.Presentation'

      rpc :Register, ::Knowledge::Request, ::Knowledge::Response
      rpc :List, ::Knowledge::Empty, stream(::Knowledge::Response)
      rpc :Withdraw, ::Knowledge::WidthdrawRequest, ::Knowledge::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
