# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: knowledge.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("knowledge.proto", :syntax => :proto3) do
    add_message "knowledge.Request" do
      optional :title, :string, 1
      optional :author, :string, 2
    end
    add_message "knowledge.Response" do
      optional :id, :int32, 1
      optional :title, :string, 2
      optional :status, :enum, 3, "knowledge.Response.Status"
      optional :presented_at, :int64, 4
      optional :author, :string, 5
    end
    add_enum "knowledge.Response.Status" do
      value :SUBMITTED, 0
      value :APPROVED, 1
      value :CANCELED, 2
    end
    add_message "knowledge.WidthdrawRequest" do
      optional :id, :int32, 1
      optional :author, :string, 2
    end
    add_message "knowledge.Empty" do
    end
  end
end

module Knowledge
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("knowledge.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("knowledge.Response").msgclass
  Response::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("knowledge.Response.Status").enummodule
  WidthdrawRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("knowledge.WidthdrawRequest").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("knowledge.Empty").msgclass
end
